add to cart form | side cart drawer
Sporn-company/liquid-to-hydrogen pull request #66
Opened 2022-11-03 19:48 UTC by zeeshan-bixlers

PDP with Cart

2022-11-03 19:54 UTC, pkubwiraBixlers requested changes
Try resolving conflicts because  all the checks are failing

2022-11-03 20:30 UTC, juniorBixlers commented on src/components/header/MobileMenu.client.jsx
> +import Cart from '../../global/Cart.client';
why you import the cart.client component with a capital C when your file name is with lowercase c?

2022-11-04 13:26 UTC, juniorBixlers approved these changes

2022-11-04 13:33 UTC, pkubwiraBixlers approved these changes
Good

2022-11-04 13:34 UTC, merged